repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff-fix
        name: Linting & sorting (ruff)
        entry: ruff check --fix --force-exclude
        types: [python]
        language: system
      - id: ruff-format
        name: Formatting (ruff)
        entry: ruff format
        types: [python]
        language: system
      - id: nbstripout
        name: Strip Jupyter notebook output (nbstripout)
        entry: nbstripout
        types: [file]
        files: (.ipynb)$
        language: system
      - id: python-bandit-vulnerability-check
        name: Security check (bandit)
        entry: bandit
        types: [python]
        args: ["--recursive", "--skip", "B101", "--exclude", "tests/"]  # Skip assert warnings and exclude tests
        language: system
      - id: codespell
        name: Checking typos
        entry: codespell
        types: [python]
        language: system
exclude: ^(.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/|venv/|.venv/)
