name: CD - Deploy Streamlit App

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]   # 👈 Must match the 'name' field in ci.yml
    types:
      - completed

permissions:
  id-token: write    # 👈 required for OIDC auth
  contents: read       

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v4

      # 2️⃣ Login sur Azure avec SP permanent
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Build Docker
      - name: Build Docker image
        run: |
          docker build -t streamlit-app:latest -f Dockerfile .

      # 4️⃣ Tag pour ACR
      - name: Tag Docker image
        run: |
          docker tag streamlit-app:latest trainingartefact.azurecr.io/streamlit-app:latest

      # 5️⃣ Login sur ACR
      - name: Login to Azure Container Registry
        run: |
          az acr login --name trainingartefact

      # 6️⃣ Push Docker image
      - name: Push Docker image to ACR
        run: |
          docker push trainingartefact.azurecr.io/streamlit-app:latest

      # 7️⃣ Deploy to Azure Container Instance
      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: devtahayassine
          dns-name-label: streamlit-app
          image: trainingartefact.azurecr.io/streamlit-app:latest
          name: streamlit-app
          location: francecentral