name: CD - Deploy Streamlit App

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]   # 👈 Must match the 'name' field in ci.yml
    types:
      - completed

permissions:
  id-token: write    # 👈 required for OIDC auth
  contents: read       

jobs:
  deploy:
    name: Deploy to Azure Container Instance
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # ✅ Only runs if CI passed
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/streamlit-app:latest .
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/streamlit-app:latest

      - name: Deploy to ACI
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          location: ${{ secrets.AZURE_LOCATION }}
          dns-name-label: streamlit-app-${{ github.run_number }}
          image: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/streamlit-app:latest
          registry-login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          registry-username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          name: streamlit-app
          ports: 8501