name: CD - Deploy Streamlit App to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/streamlit-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image to ACR
        run: |
          docker push $IMAGE_NAME

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_NAME }} \
            --image $IMAGE_NAME \
            --cpu 1 --memory 2 \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.AZURE_CLIENT_ID }} \
            --registry-password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --restart-policy Always \
            --ports 8501

      - name: Show Container URL
        run: |
          az container show \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_NAME }} \
            --query "{Status:instanceView.state, URL:ipAddress.fqdn}" \
            --output table