name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [*]

jobs:
  CI:
    name: Launching CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install uv
          CI=true make install
          
      - name: Run Pre commit hook (formatting, linting & tests)
        run: |
          source .venv/bin/activate
          # Run pre-commit hooks with bandit configuration
          pre-commit run --all-files --hook-stage pre-push --show-diff-on-failure
      
      - name: Install test dependencies
        run: |
          source .venv/bin/activate
          pip install pytest pytest-cov pytest-mock
          pip install pandas numpy scikit-learn plotly streamlit
      
      - name: Run Football Prediction Tests
        run: |
          source .venv/bin/activate
          cd tests
          python -m pytest test_football_model.py test_football_app.py test_data_creation.py -v